name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  mobile_scanner: ^3.2.0
  # qr_code_scanner: ^1.0.1 # Dependencia para escanear QR
  #printing: ^5.12.0 # Dependencia para descargar archivos pdf
  pdf: ^3.10.4
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  android_intent_plus: ^5.3.0
  device_info_plus: ^11.4.0
  http: ^1.4.0
  url_launcher: ^6.2.5
  intl: ^0.18.1
  share_plus: ^7.2.1
  printing: ^5.12.0
  flutter_svg: ^2.0.7
  build_runner: ^2.4.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  sqflite_common_ffi: ^2.3.0+1
  file_picker: ^10.2.0
  flutter_pdfview: ^1.2.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/drugs.png #<a href="https://www.flaticon.com/free-icons/medicine" title="medicine icons">Medicine icons created by Freepik - Flaticon</a>
    - assets/icons/shopping-cart.png #<a href="https://www.flaticon.com/free-icons/supermarket" title="supermarket icons">Supermarket icons created by Freepik - Flaticon</a>
    - assets/icons/pill-box.png #<a href="https://www.flaticon.com/free-icons/pill-box" title="pill box icons">Pill box icons created by Freepik - Flaticon</a>
    - assets/icons/evaluation.png #<a href="https://www.flaticon.com/free-icons/compliance" title="compliance icons">Compliance icons created by Dewi Sari - Flaticon</a>
    - assets/icons/risk.png #<a href="https://www.flaticon.com/free-icons/supply" title="supply icons">Supply icons created by gravisio - Flaticon</a>
    - assets/icons/review.png #<a href="https://www.flaticon.com/free-icons/document" title="document icons">Document icons created by vectorspoint - Flaticon</a>
    - assets/icons/compliance.png #<a href="https://www.flaticon.com/free-icons/risk" title="risk icons">Risk icons created by juicy_fish - Flaticon</a>
    - assets/icons/crisis.png #<a href="https://www.flaticon.com/free-icons/warning" title="warning icons">Warning icons created by Hilmy Abiyyu A. - Flaticon</a>
    - assets/icons/settings.png #<a href="https://www.flaticon.com/free-icons/settings" title="settings icons">Settings icons created by Freepik - Flaticon</a>
    - assets/icons/pencil.png #<a href="https://www.flaticon.com/free-icons/edit" title="edit icons">Edit icons created by Freepik - Flaticon</a>
    - assets/icons/delete.png #<a href="https://www.flaticon.com/free-icons/delete" title="delete icons">Delete icons created by Freepik - Flaticon</a>
    - assets/icons/add-user.png #<a href="https://www.flaticon.com/free-icons/add-user" title="add user icons">Add user icons created by sonnycandra - Flaticon</a>
    - assets/icons/healthcare.png #<a href="https://www.flaticon.com/free-icons/drug" title="drug icons">Drug icons created by vladimir-susakin - Flaticon</a>
    - assets/icons/notification.png #<a href="https://www.flaticon.com/free-icons/notification" title="notification icons">Notification icons created by Freepik - Flaticon</a>
    - assets/icons/medical-file.png #<a href="https://www.flaticon.com/free-icons/health" title="health icons">Health icons created by Freepik - Flaticon</a>
    - assets/icons/check.png #<a href="https://www.flaticon.com/free-icons/success" title="success icons">Success icons created by hqrloveq - Flaticon</a>
    - assets/icons/clock.png #<a href="https://www.flaticon.com/free-icons/postpone" title="postpone icons">Postpone icons created by Icontive - Flaticon</a>
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
